name: responsive_one
description: A Responsive Framework
version: 1.0.0
homepage: https://www.quantos.it
repository: https://github.com/quantosapplications/responsive_one

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
